config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets, only: [:create, :show]
  resource :search, only: [:new, :show, :edit, :create]

  namespace :admin do
    resources :railway_stations do
      patch :update_position, on: :member
    end

    resources :trains do
      resources :carriages, shallow: true
    end

    resources :routes
    resources :tickets
  end

  get 'welcome/index'

  root 'welcome#index'
end

app/models/route.rb
class Route < ActiveRecord::Base
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes

  validates :name, presence: true
  validate :stations_count

  before_validation :set_name

  private

  def set_name
    self.name ||= "#{railway_stations.first.title} - #{railway_stations.last.title}"
  end

  def stations_count
    if railway_stations.size < 2
      errors.add(:base, "Route should contain at least 2 stations")
    end
  end
end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def edit
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to [:admin, @route]
    else
      render :new
    end
  end

  def update
    if @route.update(route_params)
      redirect_to [:admin, @route]
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to admin_routes_path
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name)
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to @route
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @route.update(route_params)
      redirect_to @route
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to routes_path
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name)
  end
end

app/views/admin/routes/_form.html.erb
<%= form_for(@route) do |f| %>
  <%= render 'common/errors', resource: @route %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  

  <div class="actions">
    <%= f.submit "#{ @route.new_record? ? 'Создать' : 'Изменить' }" %>
  </div>
<% end %>

app/views/admin/routes/edit.html.erb
<h1>Изменить маршрут</h1>

<%= render 'form' %>

<%= link_to 'Назад', routes_path %>

app/views/admin/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Маршруты</h1>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @routes.each do |route| %>
    <tr>
      <td><%= route.name %></td>
      <td><%= link_to 'Показать', route %></td>
      <td><%= link_to 'Изменить', edit_route_path(route) %></td>
      <td><%= link_to 'Удалить', route, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новый маршрут', new_route_path %>

app/views/admin/routes/new.html.erb
<h1>Добавить маршрут</h1>

<%= render 'form' %>

<%= link_to 'Назад', routes_path %>

app/views/admin/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Название:</strong>
  <%= @route.name %>
</p>

<p>
  <strong>Станции:</strong>
  <% if @route.railway_stations.empty? %>
      Список пуст
  <% else %>
    <table>
      <thead>
      <tr>
        <td width="100px">Название</td>
        <td>Позиция</td>
      </tr>
      </thead>
      <tbody>
      <% @route.railway_stations.each do |station| %>
          <tr>
            <td><%station.title %></td>
            <td>
              <%= form_tag update_position_railway_station_path(station), method: :patch do %>
                <%= number_field_tag :position, station.position_in(@route) %>
                <%= hidden_field_tag :route_id, @route.id %>
                <%= submit_tag "Изменить" %>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>
</p>


<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>