config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets, only: [:create, :show]
  resource :search, only: [:new, :show, :edit, :create]

  namespace :admin do
    resources :railway_stations do
      patch :update_position, on: :member
    end

    resources :trains do
      resources :carriages, shallow: true
    end

    resources :routes
    resources :tickets
  end

  get 'welcome/index'

  root 'welcome#index'
end

app/models/train.rb
class Train < ActiveRecord::Base
  has_many :carriages

  validates :number, presence: true

  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def edit
  end

  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to [:admin, @train]
    else
      render :new
    end
  end

  def update
    if @train.update(train_params)
      redirect_to [:admin, @train]
    else
      render :edit
    end
  end

  def destroy
    @train.destroy
    redirect_to admin_trains_path
  end

  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number, :current_station_id)
  end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to @train
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @train.update(train_params)
      redirect_to @train
    else
      render :edit
    end
  end

  def destroy
    @train.destroy
    redirect_to trains_path
  end

  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number, :current_station_id)
  end
end

app/views/admin/trains/_form.html.erb
<%= form_for [:admin, @train] do |f| %>
  <%= render 'common/errors', resource: @train %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>

  <div class="field">
       <%= f.label :current_station %>
       <%= f.collection_select :current_station_id, RailwayStation.all, :id, :title %>
  </div>

  <div class="actions">
    <%= f.submit "#{ @train.new_record? ? 'Создать' : 'Изменить' }" %>
  </div>
<% end %>

app/views/admin/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td><%= link_to 'Показать', train %></td>
  <td><%= link_to 'Редактировать', edit_train_path(train) %></td>
  <td><%= link_to 'Удалить', train, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/admin/trains/edit.html.erb
<h1>Изменить поезд</h1>

<%= render 'form' %>

<%= link_to 'Назад', trains_path %>

app/views/admin/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список поездов</h1>

<table>
  <thead>
  <tr>
    <th>Номер</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
      <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить поезд', new_train_path %>

app/views/admin/trains/new.html.erb
<h1>Добавить поезд</h1>

<%= render 'form' %>

<%= link_to 'Назад', admin_trains_path %>

app/views/admin/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Номер:</strong>
  <%= @train.number %>
</p>
<p>
  <strong>На станции:</strong>
  <% if @train.current_station.present? %>
  <%= @train.current_station.title %>
    <% else %>
      Не указано
    <% end %>
</p>

<p>
  <strong>Вагоны</strong>
  <ul>
    <% @train.carriages.each do |car| %>
      <li> <%= link_to "Вагон №#{car.number}", car %></li>
      <% end %>
  </ul>
</p>

<p>
  <%= link_to "Добавить вагон", new_train_carriage_path(@train) %>
</p>

<%= link_to 'Редактировать', edit_train_path(@train) %> |
<%= link_to 'Назад', trains_path %>